// Predefined form templates for esports games

const getBgmiDefaultQuestions = () => [
  // Team Questions
  {
    id: 'team_type',
    scope: 'team',
    label: 'Team Category / Type',
    helpText: 'Select your team composition type',
    fieldType: 'dropdown',
    required: true,
    options: ['UEM Student Team', 'Outside Team', 'Mixed Team'],
    placeholder: 'Select team category',
    order: 1,
    isPublic: true,
  },
  {
    id: 'team_about',
    scope: 'team',
    label: 'Team Motto or Bio',
    helpText: 'Brief slogan or description of your squad (optional)',
    fieldType: 'short_text',
    required: false,
    options: [],
    placeholder: 'e.g. Born to dominate the battlegrounds',
    order: 2,
    isPublic: true,
  },

  // Player Questions (Applied to Captain, Starters, and Substitute)
  {
    id: 'player_name',
    scope: 'player',
    label: 'Full Name',
    helpText: 'Official legal name as per government / college ID',
    fieldType: 'short_text',
    required: true,
    options: [],
    placeholder: 'e.g. Shreyas Roy',
    order: 3,
    isPublic: true,
  },
  {
    id: 'college_name',
    scope: 'player',
    label: 'College / University',
    helpText: 'Your current academic institution name',
    fieldType: 'short_text',
    required: true,
    options: [],
    placeholder: 'e.g. University of Engineering & Management, Jaipur',
    order: 4,
    isPublic: true,
  },
  {
    id: 'college_id',
    scope: 'player',
    label: 'College ID / Enrollment Number',
    helpText: 'Student registration number or roll number',
    fieldType: 'short_text',
    required: true,
    options: [],
    placeholder: 'e.g. UEMJ/2023/BTECH/042',
    order: 5,
    isPublic: false, // Private: not exposed on public team showcase
  },
  {
    id: 'game_uid',
    scope: 'player',
    label: 'BGMI Character UID',
    helpText: 'Numeric character ID found on your BGMI profile (e.g. 5123456789)',
    fieldType: 'number',
    required: true,
    options: [],
    placeholder: 'e.g. 5123456789',
    order: 6,
    isPublic: true,
  },
  {
    id: 'game_ign',
    scope: 'player',
    label: 'BGMI In-Game Name (IGN)',
    helpText: 'Exact in-game name including special characters and clan tags',
    fieldType: 'short_text',
    required: true,
    options: [],
    placeholder: 'e.g. ApexGod丨亗',
    order: 7,
    isPublic: true,
  },
  {
    id: 'phone_number',
    scope: 'player',
    label: 'WhatsApp / Contact Phone Number',
    helpText: 'For urgent tournament match room ID & password notifications',
    fieldType: 'phone',
    required: true,
    options: [],
    placeholder: 'e.g. +91 9876543210',
    order: 8,
    isPublic: false, // Private: not exposed on public team showcase
  },
  {
    id: 'profile_photo',
    scope: 'player',
    label: 'Player Photo / Avatar',
    helpText: 'Upload a clear profile picture or esports avatar (JPG, PNG)',
    fieldType: 'image_upload',
    required: false,
    options: [],
    placeholder: '',
    order: 9,
    isPublic: true,
  },
  {
    id: 'identity_proof',
    scope: 'player',
    label: 'Identity / College Proof',
    helpText: 'Upload student ID card or enrollment proof document (Single PDF only, max 10MB)',
    fieldType: 'file_upload',
    required: true,
    options: [],
    placeholder: '',
    order: 10,
    isPublic: false, // Private: only visible to admins
  },
];

const getFreeFireDefaultQuestions = () => [
  {
    id: 'team_type',
    scope: 'team',
    label: 'Team Category / Type',
    helpText: 'Select your team composition type',
    fieldType: 'dropdown',
    required: true,
    options: ['UEM Student Team', 'Outside Team', 'Mixed Team'],
    placeholder: 'Select team category',
    order: 1,
    isPublic: true,
  },
  {
    id: 'player_name',
    scope: 'player',
    label: 'Full Name',
    helpText: 'Official legal name as per government / college ID',
    fieldType: 'short_text',
    required: true,
    options: [],
    placeholder: 'e.g. Rohit Sharma',
    order: 2,
    isPublic: true,
  },
  {
    id: 'college_name',
    scope: 'player',
    label: 'College / University',
    helpText: 'Your current academic institution',
    fieldType: 'short_text',
    required: true,
    options: [],
    placeholder: 'e.g. UEM Jaipur',
    order: 3,
    isPublic: true,
  },
  {
    id: 'college_id',
    scope: 'player',
    label: 'College ID / Enrollment Number',
    helpText: 'Student registration number',
    fieldType: 'short_text',
    required: true,
    options: [],
    placeholder: 'e.g. 1202200201',
    order: 4,
    isPublic: false,
  },
  {
    id: 'game_uid',
    scope: 'player',
    label: 'Free Fire UID',
    helpText: 'Numeric player ID found in Free Fire profile',
    fieldType: 'number',
    required: true,
    options: [],
    placeholder: 'e.g. 987654321',
    order: 5,
    isPublic: true,
  },
  {
    id: 'game_ign',
    scope: 'player',
    label: 'Free Fire IGN',
    helpText: 'In-game nickname',
    fieldType: 'short_text',
    required: true,
    options: [],
    placeholder: 'e.g. 亗•SHADOW•亗',
    order: 6,
    isPublic: true,
  },
  {
    id: 'phone_number',
    scope: 'player',
    label: 'WhatsApp / Contact Phone Number',
    helpText: 'For tournament notifications and room credentials',
    fieldType: 'phone',
    required: true,
    options: [],
    placeholder: 'e.g. +91 9123456780',
    order: 7,
    isPublic: false,
  },
  {
    id: 'profile_photo',
    scope: 'player',
    label: 'Profile Photo',
    fieldType: 'image_upload',
    required: false,
    options: [],
    placeholder: '',
    order: 8,
    isPublic: true,
  },
  {
    id: 'identity_proof',
    scope: 'player',
    label: 'Identity / College Proof',
    helpText: 'Upload student ID card or enrollment proof document (Single PDF only, max 10MB)',
    fieldType: 'file_upload',
    required: true,
    options: [],
    placeholder: '',
    order: 9,
    isPublic: false,
  },
];

module.exports = {
  getBgmiDefaultQuestions,
  getFreeFireDefaultQuestions,
};
